=== Yehorka/OOP/lab4/Course_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Courses",
            "description": "Course",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name of the course",
                    "type": "string"
                },
                "type": {
                    "description": "Type of course",
                    "type": "string"
                },
                "program": {
                    "description": "Sequence of topics",
                    "type": "array"
                },
                "teacher": {
                    "description": "Name of teacher, assigned to lead the course",
                    "type": "string"
                }
            }
        }

=== Yehorka/OOP/lab4/Course.json
[
    {
        "name": "Python",
        "type": "local",
        "program": [
            "oop",
            "pep8"
        ],
        "teacher": "Andrii"
    },
    {
        "name": "C++",
        "type": "offset",
        "program": [
            "oop",
            "C"
        ],
        "teacher": "Danylo"
    },
    {
        "name": "Test",
        "type": "offset",
        "program": [
            "damn",
            "yeah",
            "it works!"
        ],
        "teacher": "Andrii"
    }
]
